# Generated by Django 5.1.3 on 2024-11-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_full_name_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
