# Generated by Django 5.1.3 on 2024-11-19 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='categories',
        ),
        migrations.AddField(
            model_name='news',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
    ]
