# Generated by Django 5.1.3 on 2024-11-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_categories_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
